app = 'test-runner'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'
swap_size_mb = 512

[mounts]
  source = "shared"
  destination = "/shared"

[experimental]
  allowed_public_ports = [ ]

[build]

[[services]]
  internal_port = 8080
  processes = [ "app" ]
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  script_checks = [ ]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "requests"

  [[services.ports]]
    handlers = [ "http" ]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = [ "tls", "http" ]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false
    headers = { }

  [[services.http_checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/healthcheck"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1