app = 'test-runner'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'
swap_size_mb = 512

[mounts]
  destination = "/data"
  source = "data"

[build]

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '60s'
    timeout = '2s'
    grace_period = '1s'

  [[services.http_checks]]
    interval = '30s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/'
    protocol = 'http'
    tls_skip_verify = false

  [[services.http_checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthcheck'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
